syntax = "proto3";

package user.v1;

option go_package = "clirzy/user/proto;proto";

// ----------- DTO -----------

message User {
  string id = 1;
  string email = 2;
  string password_hash = 3;
}

// ----------- QUERY -----------

message GetUserByEmailRequest {
  string email = 1;
}

message GetUserByIdRequest {
  string id = 1;
}

message RegisterUserRequest {
  string email = 1;
  string password = 2;
}

message RegisterUserResponse {
  string user_id = 1;
}

// ----------- SERVICE -----------

service UserService {
  rpc GetUserByEmail(GetUserByEmailRequest) returns (User);
  rpc GetUserByID(GetUserByIdRequest) returns (User);
  rpc RegisterUser(RegisterUserRequest) returns (RegisterUserResponse);
}
