syntax = "proto3";

package auth.v1;

option go_package = "clirzy/auth/proto;proto";

// ---------- COMMON ----------

message User {
  string id = 1;
}

// ----------- QUERY -----------

message ValidateAccessTokenRequest {
  string access_token = 1;

}

message ValidateAccessTokenResponse {
  string user_id = 1;
  repeated string roles = 2;
}

// ---------- SERVICE ----------

service AuthService {
  rpc ValidateAccessToken(ValidateAccessTokenRequest)
    returns (ValidateAccessTokenResponse);
}
