// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.1
// source: seller.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SellerService_GetSellerByID_FullMethodName     = "/seller.v1.SellerService/GetSellerByID"
	SellerService_GetSellerByUserID_FullMethodName = "/seller.v1.SellerService/GetSellerByUserID"
)

// SellerServiceClient is the client API for SellerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SellerServiceClient interface {
	GetSellerByID(ctx context.Context, in *GetSellerByIdRequest, opts ...grpc.CallOption) (*Seller, error)
	GetSellerByUserID(ctx context.Context, in *GetSellerByUserIdRequest, opts ...grpc.CallOption) (*Seller, error)
}

type sellerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSellerServiceClient(cc grpc.ClientConnInterface) SellerServiceClient {
	return &sellerServiceClient{cc}
}

func (c *sellerServiceClient) GetSellerByID(ctx context.Context, in *GetSellerByIdRequest, opts ...grpc.CallOption) (*Seller, error) {
	out := new(Seller)
	err := c.cc.Invoke(ctx, SellerService_GetSellerByID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellerServiceClient) GetSellerByUserID(ctx context.Context, in *GetSellerByUserIdRequest, opts ...grpc.CallOption) (*Seller, error) {
	out := new(Seller)
	err := c.cc.Invoke(ctx, SellerService_GetSellerByUserID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SellerServiceServer is the server API for SellerService service.
// All implementations must embed UnimplementedSellerServiceServer
// for forward compatibility
type SellerServiceServer interface {
	GetSellerByID(context.Context, *GetSellerByIdRequest) (*Seller, error)
	GetSellerByUserID(context.Context, *GetSellerByUserIdRequest) (*Seller, error)
	mustEmbedUnimplementedSellerServiceServer()
}

// UnimplementedSellerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSellerServiceServer struct {
}

func (UnimplementedSellerServiceServer) GetSellerByID(context.Context, *GetSellerByIdRequest) (*Seller, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSellerByID not implemented")
}
func (UnimplementedSellerServiceServer) GetSellerByUserID(context.Context, *GetSellerByUserIdRequest) (*Seller, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSellerByUserID not implemented")
}
func (UnimplementedSellerServiceServer) mustEmbedUnimplementedSellerServiceServer() {}

// UnsafeSellerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SellerServiceServer will
// result in compilation errors.
type UnsafeSellerServiceServer interface {
	mustEmbedUnimplementedSellerServiceServer()
}

func RegisterSellerServiceServer(s grpc.ServiceRegistrar, srv SellerServiceServer) {
	s.RegisterService(&SellerService_ServiceDesc, srv)
}

func _SellerService_GetSellerByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSellerByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerServiceServer).GetSellerByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerService_GetSellerByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerServiceServer).GetSellerByID(ctx, req.(*GetSellerByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellerService_GetSellerByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSellerByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerServiceServer).GetSellerByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerService_GetSellerByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerServiceServer).GetSellerByUserID(ctx, req.(*GetSellerByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SellerService_ServiceDesc is the grpc.ServiceDesc for SellerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SellerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seller.v1.SellerService",
	HandlerType: (*SellerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSellerByID",
			Handler:    _SellerService_GetSellerByID_Handler,
		},
		{
			MethodName: "GetSellerByUserID",
			Handler:    _SellerService_GetSellerByUserID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seller.proto",
}
